#!/bin/bash

SCRIPT_NAME=template
SCRIPT_DESCRIPTION="Template script."
SCRIPT_VERSION=0.1
SCRIPT_AUTHOR=Slithery



# Script usage
#

usage () { cat <<-USAGETXT

	$SCRIPT_NAME
	v$SCRIPT_VERSION by $SCRIPT_AUTHOR
	
	$SCRIPT_DESCRIPTION
	
	  USAGE:  $SCRIPT_NAME [OPTIONS] VAR1

	  OPTIONS:  -h     Display this help.
	            -V     Show version.

USAGETXT
}

# Declare getopts variables
#

#EXAMPLE_OPTION_SWITCH=0
#EXAMPLE_OPTION_VARIABLE=""


# Options
#

while getopts :hVef: flag
	do
    case "$flag" in
    (h) usage; exit 0;;
    (V) echo "$SCRIPT_VERSION"; exit 0;;
#   (e) EXAMPLE_OPTION_SWITCH=1;;				# Add e to getopts string.
#   (f) EXAMPLE_OPTION_VARIABLE="$OPTARG";;		# Add f: to getopts string.
    (*) echo "Invalid option, use -h for help."; exit 1;;
    esac
	done

shift $(($OPTIND - 1))

VAR1=$1

# Main script.
#


exit
